apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: ffc-demo-payment-service
version: 1.0.0
dependencies:
- name: ffc-helm-library
  version: ^1.0.0
  repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
