{{- include "ffc-helm-library.container-secret" (list . "ffc-demo-payment-service.container-secret") -}}
{{- define "ffc-demo-payment-service.container-secret" -}}
stringData:
  {{- if .Values.appInsights.key }}
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ quote .Values.appInsights.key }}
  {{- end }}
  POSTGRES_USERNAME: {{ .Values.postgresService.postgresUser | quote }}
{{- end -}}
